// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhdzdSob6tQWux1SlDAW4G2Ua9n6rBSNI',
    appId: '1:783694400766:web:c865f8ab332007adb4e9af',
    messagingSenderId: '783694400766',
    projectId: 'tvpp2-894e0',
    authDomain: 'tvpp2-894e0.firebaseapp.com',
    storageBucket: 'tvpp2-894e0.appspot.com',
    measurementId: 'G-TT8SGQCX12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChcvxQz7lOm3o3mssSm-6eEv7Fh_6yRtE',
    appId: '1:783694400766:android:7df25cbae6766229b4e9af',
    messagingSenderId: '783694400766',
    projectId: 'tvpp2-894e0',
    storageBucket: 'tvpp2-894e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8ytSkrmnqBY2VQqD60e7BanyUiSrLuNc',
    appId: '1:783694400766:ios:983673a20b162630b4e9af',
    messagingSenderId: '783694400766',
    projectId: 'tvpp2-894e0',
    storageBucket: 'tvpp2-894e0.appspot.com',
    iosBundleId: 'com.example.pp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8ytSkrmnqBY2VQqD60e7BanyUiSrLuNc',
    appId: '1:783694400766:ios:24c1e9aff312303eb4e9af',
    messagingSenderId: '783694400766',
    projectId: 'tvpp2-894e0',
    storageBucket: 'tvpp2-894e0.appspot.com',
    iosBundleId: 'com.example.pp2.RunnerTests',
  );
}
